Repository Pluspo/pluspo, pull requests merged in 2022-09, with the labels that each got.

#42 Fix: header
  app/views/shared/_header.html.slim
Labels: 👾レイアウト, 👩‍🎨 デザイン

#41 Add-place_table
  app/views/places/_show.html.slim
  app/views/places/_tables.html.slim
Labels: 👩‍🎨 デザイン

#43 Add: 施設一覧画面の右側、施設詳細を追加.
  app/assets/images/taito_riverside_sports_center.png
  app/views/layouts/application.html.slim
  app/views/places/_show.html.slim
Labels: 👾レイアウト, 👩‍🎨 デザイン

#55 TOPページのデザインを整えた
  app/assets/images/logo_no_subtitle.png
  app/assets/stylesheets/application.css
  app/javascript/application.js
  app/javascript/custom/calendar.js
  app/views/layouts/application.html.slim
  app/views/places/_tables.html.slim
  app/views/shared/_header.html.slim
  config/importmap.rb
Labels: 👾レイアウト, 👩‍🎨 デザイン

#52 Add: places・sports・areas・areas_sports・batchesテーブル作成
  app/models/area.rb
  app/models/area_sport.rb
  app/models/batch.rb
  app/models/place.rb
  app/models/shedule.rb
  app/models/sport.rb
  db/migrate/20220905033400_create_places.rb
  db/migrate/20220905035232_create_sports.rb
  db/migrate/20220905055621_create_areas.rb
  db/migrate/20220905060535_create_area_sports.rb
  db/migrate/20220905062721_create_sport_shedules.rb
  db/migrate/20220905083530_create_batches.rb
  db/migrate/20220906022645_change_column_null_areas.rb
  db/migrate/20220906022941_change_column_null_places.rb
  db/migrate/20220906023145_change_column_null_sport_shedules.rb
  db/migrate/20220906024038_add_note_to_areas.rb
  db/migrate/20220906025026_add_message_to_places.rb
  db/migrate/20220906072352_change_sport_shedules_to_shedules.rb
  db/migrate/20220906074024_add_started_at_finished_at_to_batches.rb
  db/migrate/20220906075710_change_column_null_batches.rb
  db/migrate/20220907010856_remove_address_from_areas.rb
  db/migrate/20220907011855_remove_cycles_from_shedules.rb
  db/migrate/20220907021929_add_cycle_to_batches.rb
  db/migrate/20220907063630_add_index_places_city.rb
  db/migrate/20220907064527_add_index_shedules_started_at_finished_at.rb
  db/migrate/20220908020554_add_status_to_areas.rb
  db/schema.rb
Labels: 💡 機能追加, 🔥優先

#60 【WIP】デモデータを動的に表示
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/controllers/places_controller.rb
  app/decorators/application_decorator.rb
  app/decorators/place_decorator.rb
  app/decorators/schedule_decorator.rb
  app/models/area.rb
  app/models/area_sport.rb
  app/models/batch.rb
  app/models/place.rb
  app/models/schedule.rb
  app/models/shedule.rb
  app/models/sport.rb
  app/views/places/_show.html.slim
  app/views/places/_tables.html.slim
  config/application.rb
  config/environments/development.rb
  config/locales/ja.yml
  db/fixtures/01_place.rb
  db/fixtures/development/02_schedule.rb
  db/migrate/20220920022516_rename_status_column_to_areas.rb
  db/migrate/20220920023808_rename_shedules_to_schedules.rb
  db/migrate/20220920051959_change_column_to_schedules.rb
  db/migrate/20220921064056_remove_columns_from_areas.rb
  db/migrate/20220921064812_remove_column_from_batches.rb
  db/migrate/20220921065232_change_columns_from_batches.rb
  db/migrate/20220923023328_change_column_from_areas.rb
  db/schema.rb
  lib/tasks/auto_annotate_models.rake
  spec/rails_helper.rb
Labels: 💡 機能追加, 🔥優先, 🐳 修正
